def help():
    print("These are all the allowed commands: ")
    print()
    print("Commands related to versioning controls ")
    print("enable          Enable versioning of a file")
    print("disable         Disable versioning of a file")
    print()
    print("Commands related to saving the version ")
    print("save            Saves version of a file")
    print()
    print("Commands related to version checking ")
    print("check           Checks if versioning is enabled or disabled for a file")
    print("track           Gives the latest version of a file")
    print()
    print("Commands related to getting info about a version ")
    print("info            Gives all the metadata about a particular version")
    print()
    print("Commands related to opening a particular version")
    print("show            Opens a particular version in vs code")
    print("checkout        To replace a particular file with the input version")
    print()
    print("Commands related to tags of versions")
    print("add_tags         Add tags to a particular version")
    print("display          Display tags of a particular version")
    print("remove           Remove tags of a particular version")
    print()
    print("Commands related to getting details of a particular question")
    print("details           Provides details of the question according to Leetcode")
    print()
    print("Commands related to LLM help")
    print("assist            Helps find mistakes in code with the help of an LLM")
    print()
    
    


